### PR TITLE
1.7.1

### PR DESCRIPTION
**Pull request by AlexFe96**
Made debounce equal number of components in form json.

### CODE REVIEW

**Comment by randallknutson** [comment]
The 500 is the delay for the debounce. What is the reason for this change? Is it taking too long before triggering change? Having a few milliseconds may not be long enough.

**Comment by AlexFe96** [comment]
Yes, it is. After updated to react 16.x, it is taking too long before triggering email input change. I sent video demonstration on your email address. The video shows huge the delay, in the console I call the console.log to each field changes.

**Comment by randallknutson** [comment]
Would it be better to decrease the delay to 100ms or something? The component length seems rather arbitrary for the delay.

**Comment by AlexFe96** [comment]
Maybe 50ms?

**Comment by AlexFe96** [comment]
What will i have to do? New commit with current version or something else?

**Comment by AlexFe96** [comment]
Hi Randall. Can you push my changes? My boss requires to close task but i
cant't because need to change delay. Merge plz...

вт, 31 дек. 2019 г. в 16:59, Randall Knutson <notifications@github.com>:

**Comment by randallknutson** [comment]
This is published as version 1.7.2 since there was already a 1.7.1

**Pull request merged**
