### PR TITLE
removed form components

### PR DESCRIPTION
**Pull request by aminmc**
Related to #208

### CODE REVIEW

**Comment by YuryRybakSoftensity** [comment]
@aminmc Sorry for the delay, I think we will merge your PR for now, but we would like to understand your usecase, because logic with components makes sense for me and I'm wonding what might be wrong with it.

**Comment by aminmc** [comment]
Hi there

I can understand what you’ve done too but I’ve been struggling to work out why the exception related to the issue is being thrown. Happy to walk through the code I have with you.

**Comment by aminmc** [comment]
@YuryRybakSoftensity 
I have this bit of code:

```js
updateForm={ (jsonSchema) => {
                   //store json schema in state
                }}
```
combined with the code in the FormBuilder causes this issue.

**Comment by YuryRybakSoftensity** [comment]
@aminmc I don't think it helps me :)
Maybe you could create Gist, JSFiddle or a repo with the issue reproduced?

**Comment by aminmc** [comment]
@YuryRybakSoftensity Working on trying to create a codesandbox however getting strange error when trying to use rc.3
```js
Could not find module in path: 'core-js/2.6.9/modules/es.symbol' relative to '/node_modules/formiojs/4.0.0-rc.4/components/_classes/nested/NestedComponent.js'
```

Will try to get an example to you however we've been blocked with this issue for a long time now and we're unable to release our application due to this.

**Comment by franke-mc** [comment]
@aminmc: Can you reproduce the issue using something like [this](https://github.com/formio/react-formio/files/3368992/formio-components-all-lost.sh.txt)? As I mentioned in https://github.com/formio/react-formio/issues/214#issuecomment-508111463 , I had seen your error, too, but these days, even with the exact versions you originally mentioned in #208, I only see the two JS warnings mentioned https://github.com/formio/react-formio/issues/214#issuecomment-509264954 ...

**Comment by aminmc** [comment]
@YuryRybakSoftensity  here is an example

https://codesandbox.io/s/practical-sun-pt3vm

if you put a component inside you'll see the error. Ignore the missing css

**Comment by YuryRybakSoftensity** [comment]
@aminmc Thank you for the example, it really helps!
I was able to identify the issue and currently working on a fix.

**Comment by aminmc** [comment]
@YuryRybak any updates on a fix for this?

**Comment by aminmc** [comment]
Hello. Is there any updates on this? This issue has been open for a while now and we’re unable to upgrade formio js.

**Pull request closed without merging**
